"""third migration

Revision ID: 432837312054
Revises: d4ee20980475
Create Date: 2022-03-12 10:04:08.818244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '432837312054'
down_revision = 'd4ee20980475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    # ### end Alembic commands ###
