"""add like model

Revision ID: c7c42f726bd2
Revises: e193c93548e4
Create Date: 2022-03-14 06:57:57.851589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7c42f726bd2'
down_revision = 'e193c93548e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('like_author', sa.Integer(), nullable=False),
    sa.Column('like_pitch', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['like_author'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['like_pitch'], ['pitches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    # ### end Alembic commands ###
