"""Create comments model

Revision ID: e193c93548e4
Revises: facaeeb2525a
Create Date: 2022-03-13 22:05:37.761802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e193c93548e4'
down_revision = 'facaeeb2525a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=200), nullable=False),
    sa.Column('comment_author', sa.Integer(), nullable=False),
    sa.Column('comment_pitch', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_author'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['comment_pitch'], ['pitches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    # ### end Alembic commands ###
